title: Nguyen Yen Chi # your name (or website title) here
logo: "/images/NYC_ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Junior IT BA with a demonstrated history of working in the education management industry. Skilled in Data and Business Analyst, Research, English.  
 <br><br>
 Aspiring Data Analyst
 <br><br>
 <a href="https://www.linkedin.com/in/nguyen-yen-chi-a874aaba/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: EQNBGFDUGM6C # your Google Analytics tracking ID here
